### ISSUE TITLE
Addon fails to work on YouGlish.com

### ISSUE THREAD

**Issue by MetroidCatcher** [da2x/youtube-nocookie#1]
What the title says. If I disable the extension, it works, but for some reason, if it's active it fails to work.

Some technical info:
Windows 10 (1809) 64 bit
Firefox 68.0
Privacy Enhanced Mode for Embedded YouTube 1.2.0

**Comment by da2x** [comment]
Duplicate of issue #2. I don’t have a strategy to deal with this situation at the moment.
